# Generated by Django 2.2.10 on 2020-05-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sample_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_10',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_2',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_3',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_4',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_5',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_6',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_7',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_8',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sample_9',
        ),
        migrations.AddField(
            model_name='item',
            name='price_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段1'),
        ),
        migrations.AddField(
            model_name='item',
            name='price_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='値段2'),
        ),
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='item',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
