# Generated by Django 2.2.10 on 2020-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200527_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price_1',
        ),
        migrations.RemoveField(
            model_name='item',
            name='price_2',
        ),
        migrations.AddField(
            model_name='item',
            name='current_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='現価'),
        ),
        migrations.AddField(
            model_name='item',
            name='list_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='定価'),
        ),
    ]
