# Generated by Django 3.0.7 on 2020-06-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200529_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.TextField(blank=True, null=True, verbose_name='作成者2'),
        ),
    ]
